### ISSUE TITLE
missing bin files

### ISSUE THREAD

**Issue by irmen** [Klaus2m5/6502_65C02_functional_tests#10]
Hello!
Could you add the missing bin file for the interrupt tests and the decimal tests?
(and seeing that the other tests got an update a few weeks ago, perhaps update the two other bin files with the recent changes?)
Thanks a lot!

**Comment by Klaus2m5** [comment]
Hello,
the bin files never were my preferred way of distributing the test, as all parts must be configured to suit your needs. The configuration requirement is even more substantial for the interrupt test and also for the decimal test. In the interrupt test you must configure an IO port as a source to inject signals into the IRQ, NMI and RESET pins. The decimal test must be configured to cater for deviations in the 6502 versions (6502, 65C02 & 65C816) and the required accuracy (flags, invalid BCD operands). There is no "one size fits all". So if you want to use these tests I'm afraid you have to go through the pain of assembling them yourself.
cheers, Klaus

**Comment by irmen** [comment]
Understandable. I was mainly asking because so far I haven't been able to reproduce the exact same binary output from the two provided bin files by assembling the source code.  


*edit* nevermind, just discovered that I had to set the zp start address to $0 instead of $a.  I'm all good :)

**Comment by Klaus2m5** [comment]
Yes, instead of
  org zero_page
I wrote
  org 0
  ds zero_page
to create the bin files.
