### ISSUE TITLE
as65.exe-generated .bin files need 10byte padding at the beginning

### ISSUE THREAD

**Issue by problame** [Klaus2m5/6502_65C02_functional_tests#11]
I tried to compile the .bin files myself on a Windows 10 VM, using the zipped as65.exe.

```
 ./as65.exe -l -m -w -h0 ../6502_functional_test.a65
```

Somehow, the resulting .bin file's codes segment starts 10bytes before `0x0400`.

I fixed this using 

```
dd if=6502_functional_test.bin of=6502_functional_test.bin.padded bs=1 seek=10 
```

Any idea why this happens?

**Comment by Klaus2m5** [comment]
To create a bin file you must replace
```
       org zero_page
```
in the assembler source with
```
        org 0               ;edited to provide binaries loading from 0
        ds  zero_page
```
to add the required padding for a bin file.
