### ISSUE TITLE
Issue with the functional test (TSX, LDA $102,X)

### ISSUE THREAD

**Issue by cbeust** [Klaus2m5/6502_65C02_functional_tests#13]
I have a question about this portion of your functional test
```
37c3 : ba                       tsx             ;test break on stack
37c4 : bd0201                   lda $102,x
                                cmp_flag 0      ;break test should have B=1 & unused=1 on stack
37c7 : c930            >            cmp #(0      |fao)&m8    ;expected flags + always on bits
```

This is what I see in my emulator:

```
37C3: BA         TSX                   A=42 X=FB Y=48 S=FB P=B1 PC=$37C3 P={$B1 N=1 V=0 B=1 D=0 I=0 Z=0 C=1} SP={$FB stack:[$1FF:$09 $1FE:$CF $1FD:$00 $1FC:$30 ]}
37C4: BD 02 01   LDA $0102,X           A=00 X=FB Y=48 S=FB P=33 PC=$37C4 P={$33 N=0 V=0 B=1 D=0 I=0 Z=1 C=1} SP={$FB stack:[$1FF:$09 $1FE:$CF $1FD:$00 $1FC:$30 ]}
37C7: C9 30      CMP #$30              A=00 X=FB Y=48 S=FB P=B0 PC=$37C7 P={$B0 N=1 V=0 B=1 D=0 I=0 Z=0 C=0} SP={$FB stack:[$1FF:$09 $1FE:$CF $1FD:$00 $1FC:$30 ]}
37C7: D0 30      BNE $37C7             A=00 X=FB Y=48 S=FB P=B0 PC=$37C7 P={$B0 N=1 V=0 B=1 D=0 I=0 Z=0 C=0} SP={$FB stack:[$1FF:$09 $1FE:$CF $1FD:$00 $1FC:$30 ]}
```

As you can see, my stack contains the expected value (#$30), however, `TSX` followed by `LDA $102,X` points toward the next available spot of the stack, not the current value. So I get 0 and the test fails.

Am I missing something?

**Comment by Klaus2m5** [comment]
Hi Cedric,

the §30 that you are seeing is a result of a PHP that stores the current 
Processor state at the beginning of the interrupt handler directly at 
label irq-trap. This is also the reason for the offset of $102,x as what 
the BRK has stored from the top of the stack down is its own address +2 
(low, high) and the processor state at $1FD = $00. So The BRK does not 
force a 1 in the BRK- and the unused-bit being stored on the stack.

If you are interested in the reasoning why the test expects $30 to be 
stored as the processor state by a  BRK:
http://forum.6502.org/viewtopic.php?f=2&t=2241&hilit=request+for+verification&start=30#p20914

cheers, Klaus


Am 01.09.2020 um 00:00 schrieb Cedric Beust:

**Comment by cbeust** [comment]
Appreciate the response, Klaus! A bit too late for me to parse it so I'll go over it tomorrow, but just to clarify: I wasn't asking about the value #$30, which I have in the stack, but about the arithmetic of "TSX" followed by "LDA $102,X", which in my calculations will always go past the stack.

For example, with an empty stack, S=$FF, so

TSX =>  X=$FF
LDA $102,X => LDA $201  // beyond the stack

I must be missing something obvious.

**Comment by Klaus2m5** [comment]
Cedric, if the stack pointer is $FF the stack is empty. In your case the 
stack pointer is $FB. To interrogate  what is on the stack is above the 
next free stack location (what the interrupt handler´s PHP has stored, 
you would have to add $100 + 1 +$FB. However, at this point the test 
looks for what has been stored by the BRK, not by the PHP which is $100 
+ 2 +$FB. That is, what TSX followed by LDA $102,x does.

Remember the stack works LIFO, down for things you push onto the stack, 
up for things you pop off the stack. If you want to interrogate values 
without popping them off the stack, one has to resort to the TSX LDA 
$101,x method. LDA $102,x just reads the next to last value. Obviously 
this method would not work on a wrap around of the stack. But that is 
not happening here.

Am 01.09.2020 um 10:25 schrieb Cedric Beust:

**Comment by cbeust** [comment]
Thanks for your explanation, Klaus, I was able to adjust my emulator to your recommendations and it now passes all your tests.

Thanks for this very valuable resource!
