### ISSUE TITLE
Including a .bin file from your repo

### ISSUE THREAD

**Issue by mortenjc** [Klaus2m5/6502_65C02_functional_tests#15]
Hi

This is not a ticket - but I haven't got your email address, so ;-)

I am one of countless others who are having fun implementing a 6502 simulator. I have included 
one bin file from your repo (6502_functional_test.bin). How do you want me to credit you?

Best

Morten

**Comment by Klaus2m5** [comment]
Morten,

there is no need to credit me for the distribution of a bin file from my repo. However, it is a diagnostic tool and pretty much useless without the listing. The listing in turn does contain the license and information about the author anyway.

cheers, Klaus
