### ISSUE TITLE
Trap in 65c02 functional test code

### ISSUE THREAD

**Issue by chrbayer** [Klaus2m5/6502_65C02_functional_tests#16]
Hi, I have a problem with the 65c02 test code:Two uninitialized memory spaces are compared and this leads to a trap.

Should really the index register y be used? x is cleared jut before. But then a loop over y is programmed... 

; testing load / store accumulator LDA / STA (zp)
.
.
.

```
        trap_ne
        cpx #$99
        trap_ne     ;x altered during test
        cpy #$66                                                              <= Here it is clear that y is #$66
        trap_ne     ;y altered during testorg
        ldx #0
tstai2  lda abst,y                                                           <= Here $0205 + $66 = $026B is read, which is uninitialized
        eor #$c3
        cmp abs1,y                                                           <= Here $0210 + $66 = $0276 is read, which is uninitialized
        trap_ne     ;store to indirect data                           <= Compare fails and trap occurred
        txa
        sta abst,y  ;clear
        dey
        bpl tstai2
        tsx
        cpx #$ff
        trap_ne     ;sp push/pop mismatch
        next_test
```

**Comment by Klaus2m5** [comment]
There is a LDY #3 just ahead of LDX #0 in the original source code, which seems to be missing from your copy.

>         ldy #3      ;testing store result
>         ldx #0 
> tstai2  lda abst,y 
>         eor #$c3 
>         cmp abs1,y

**Comment by chrbayer** [comment]
Oh yes, it has been accidentally overwritten by mistake. what a shame....  I will just re-test, this looks much better :-)
Now it is fine, thanks
