### ISSUE TITLE
Version of binary examples differs from latest source release

### ISSUE THREAD

**Issue by Esisxnem** [Klaus2m5/6502_65C02_functional_tests#17]
First, thank you very much for this fantastic suite.
This is not really an issue, but I've noticed that the compiled examples belong to a previous version. The 6502 LST file states 2015 and the 65c02 LST file states 2017.
I've compiled myself the 6502 and I've obtained a different HEX/BIN and LST file.

Raul

**Comment by Klaus2m5** [comment]
Yes, the folder bin_files does not contain the latest fixes and was only 
meant to be a quick and dirty way to allow usage of the tests without 
having to assemble them with the correct assembler. The preferred usage 
is (as you did) assembling the source files yourself and therefore being 
able to set switches and addresses to your needs. The bin_files version 
however should still run without errors as the fixes just add specific 
tests for previously undetected errors in the emulation or FPGA program.
