### ISSUE TITLE
Add option to turn off decimal mode specific tests

### ISSUE THREAD

**Issue by bgourlie** [Klaus2m5/6502_65C02_functional_tests#2]
I'm writing a nes emulator which uses a custom NMOS 6502 that doesn't implement decimal mode ADC/SBC.  It would be nice to have an option not to test this functionality.

**Comment by Klaus2m5** [comment]
In the source file you can simply delete the last two tests including the preceeding next_test macro but keeping the final check of the test_case (lines 5104-5242). You may also delete  the subroutine labeled chkdad.

I am currently away from home and it may take a few weeks to add a configuration switch to disable decimal tests.

If you want to use the pre-configured downloadable binary you need to patch $32e8 with $4c8d33 (JMP $338d).

**Comment by bgourlie** [comment]
Thanks Klaus!  I really appreciate the response and all the work you've done on this.

**Comment by Klaus2m5** [comment]
I have added a configuration switch to the source file. The binaries still need the patch as I can't make binaries with all possible configuration options. However, when the test stops with an error for a decimal add or subtract all non decimal tests have completed successfully and error free.
