### ISSUE TITLE
"Bootable ROM"  extension

### ISSUE THREAD

**Issue by szilvasyz** [Klaus2m5/6502_65C02_functional_tests#6]
Hi Klaus,

I have just been writing a small 6502 simulator in Python3 for supporting my own FPGA developments, and found your very useful test suite. I have made a little modification in your asm code to be able to produce a complete ROM image with reset vector pointing to the start of the testing code. The reset vector is written back to point original "res_trap" vector, right after the start. This feature is useful when you start the testing code on a simple virtual microcomputer which has no other executable code apart from this testing suite -> after "powering on" this machine, the test code is started immediately by the reset mechanism. 

If you find this extension usable, please feel free to lift it into your test code. Attached zip contains the complete modified asm.

Thank you for attention,
Zoltan

[6502_functional_test.zip](https://github.com/Klaus2m5/6502_65C02_functional_tests/files/2999407/6502_functional_test.zip)

**Comment by Klaus2m5** [comment]
Hi Zoltan,

thanks for sharing your modification. However, at this time I don't think it is a commonly needed feature. My opinion may of course change if I get to know more cases where this modification would be helpfull.

cheers, Klaus
