### ISSUE TITLE
Possible test escape: ROR with carry clear can set zero flag

### ISSUE THREAD

**Issue by BigEd** [Klaus2m5/6502_65C02_functional_tests#7]
A bug reported in the a6502 emulator project indicates a possible test hole, because I believe that project passes this test suite. See
https://github.com/BigEd/a6502/issues/2

> when carry flag is cleared and register value is 0x01, it fails to set zero flag.

(I haven't yet been able to test this myself.)

**Comment by Klaus2m5** [comment]
Shifts have a limited set of 4 patterns with and without carry in the test. While the test will check if the zero flag gets cleared after you shift a carry in there is no pattern to actually check that the zero flag is set after the last 1 is shifted out to the carry flag. The pattern only checks for the flag to remain set if you shift §00 with carry clear. This is also true for the other shift ops like LSR, ASL and ROL.

I will add additional shift test patterns ($01, $80). It may take a while as I am currently away from home.

**Comment by BigEd** [comment]
That sounds great, thanks!

**Comment by Klaus2m5** [comment]
Finally I added the required test patterns. I tested the change with the Kowalski simulator. However, I currently do not have a test platform to recreate the original bug and wether it is now detected.
