### ISSUE TITLE
AS65 Assembler is difficult to find

### ISSUE THREAD

**Issue by flyingzebra** [Klaus2m5/6502_65C02_functional_tests#9]
As indicated in the source code, I followed the link to the AS65 assembler at the indicated link: http://www.kingswood-consulting.co.uk/assemblers/  which is unfortunately broken.  As a retro-computing fan, I see a lot of these issues happening.  In fact, nowadays it would be not a bad idea to simply include the compiler into the project to avoid any external dependencies.  Another option would be to re-write the source-code to run on more widespread assemblers, or publish compiled hex-code listings alongside.

**Comment by Klaus2m5** [comment]
I attached the assembler as a temporary solution below.
[as65_142.zip](https://github.com/Klaus2m5/6502_65C02_functional_tests/files/4021707/as65_142.zip)

**Comment by BigEd** [comment]
Just for reference:
There's a copy of AS65 by Frank Kingswood (or maybe Frank Vorstenbosch) here:
https://github.com/hculpan/h6502/tree/master/as65
which is, I think the latest. There's an archive of the original page here:
http://web.archive.org/web/20190301123637/http://www.kingswood-consulting.co.uk/assemblers/

**Comment by Klaus2m5** [comment]
I have added AS65 to the repository. The source will not be converted to other assemblers by me, but you may find that other users' forked versions have been converted. For example GitHub user amb5l has
a CA65 compatible version in his repository.

**Comment by flyingzebra** [comment]
Thank you very much, this is very helpful !
Best regards
